### ISSUE TITLE
generate PDF

### ISSUE THREAD

**Issue by vBaMnup** [littleknitsstory/backend#63]
# F -> text -> db -> cleint -> data -> db
                        #      V
                        #    generate PDF

data -> html + jijna2  + pdfkit -> pdf 

def generate_pdf(data) -> pdf
    pass

test generate_pdf
```
with tempfile.TemporaryDirectory(dir=APP_PATH) as tmpdirname:
    file_path = f"{tmpdirname}/{uuid.uuid4()}.pdf"
    try:
        pdfkit.from_string(
            input=template_string, output_path=file_path, options=options,
        )
        logger.debug(f"Successfully render from html to pdf file - {file_path}")
    except Exception as error:
        logger.warning(
            f" Warning lib pdfkit not render - {file_path} with error {error}"
        )

```

2)  FASTapi (background tasks) + POST ---> 
GET --> url --404-> PDF 

3) AWSLamba

 router.py
gengerate.py

**Comment by 63phc** [comment]
post 
views -> def generate_html(text) : return render_html()
